import type { WeaponDefinition } from '../WeaponDefinition';

/** Bolt action precision rifle: one shot, then a long cycle before the next. */
export const L96: WeaponDefinition = {
  id: 'l96',
  name: 'L96A1',
  caliber: '7.62 x 51',
  fireModes: ['semi'],
  rpm: 90,
  magazineSize: 10,
  reloadTime: 3.4,
  equipTime: 1,
  boltCycleTime: 1.15,
  recoil: {
    vertical: 0.086,
    horizontal: 0.016,
    climbPerShot: 0,
    maxClimb: 1,
    randomness: 0.22,
    snappiness: 34,
    recoverySpeed: 3.6,
    recoveryFraction: 0.46,
    kickback: 0.16,
    punch: 0.3,
    shake: 1,
  },
  spread: {
    base: 0.0009,
    adsMultiplier: 0.08,
    perShot: 0.002,
    max: 0.006,
    recovery: 0.02,
    movePenalty: 0.012,
  },
  ads: {
    time: 0.42,
    fov: 12,
    sensitivityMultiplier: 0.3,
    recoilMultiplier: 1,
    scope: {
      hideViewModelAt: 0.72,
      magnificationLabel: '6x',
    },
  },
  projectile: {
    velocity: 915,
    gravityMultiplier: 1,
    drag: 0.0006,
    maxDistance: 900,
    damage: 95,
  },
  movementMultiplier: 0.85,
  adsMovementMultiplier: 0.25,
  viewModel: {
    hipPosition: [0.19, -0.18, -0.42],
    hipRotation: [0.02, -0.05, 0.02],
    adsDistance: 0.16,
    swayAmount: 1.2,
    bobAmount: 1.1,
    weight: 11,
  },
  audio: {
    gain: 1,
    bodyFrequency: 48,
    crackFrequency: 820,
    decay: 0.3,
    tailDecay: 1,
    mechanical: 0.6,
    reverb: 1,
  },
};
